FROM python:3.11-slim-bookworm AS tmp-stage1
COPY installer/install_model_bert_base_cased.py install_model_bert_base_cased.py
RUN pip3 install --upgrade pip setuptools && \
    pip install pycrawlers && \
    pip install transformers && \
    python3 install_model_bert_base_cased.py && \
    cp -r model/base/hub model/tokenizer

FROM ghcr.io/1panel-dev/maxkb-vector-model:v1.0.1 AS vector-model

FROM alpine AS tmp-stage2
COPY --from=vector-model /opt/maxkb/app/model /opt/maxkb-app/model
COPY --from=vector-model /opt/maxkb/app/model/base/hub /opt/maxkb-app/model/tokenizer
COPY --from=tmp-stage1 model/tokenizer /opt/maxkb-app/model/tokenizer
RUN rm -rf /opt/maxkb-app/model/embedding/shibing624_text2vec-base-chinese/onnx
RUN apk add --update --no-cache curl && \
    mkdir -p openai-tiktoken-cl100k-base && \
    curl -Lf  https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken > openai-tiktoken-cl100k-base/cl100k_base.tiktoken && \
    mv -f openai-tiktoken-cl100k-base /opt/maxkb-app/model/tokenizer/


FROM scratch
COPY --from=tmp-stage2 /opt/maxkb-app/model /opt/maxkb-app/model